from __future__ import annotations

import html
import re
from datetime import datetime, timezone
from email.utils import format_datetime
from pathlib import Path
from urllib.parse import quote


def build_site(output_dir: Path = Path("output"), site_dir: Path = Path("site")) -> Path:
    site_dir.mkdir(parents=True, exist_ok=True)
    digests_dir = site_dir / "digests"
    digests_dir.mkdir(parents=True, exist_ok=True)

    digest_files = sorted(output_dir.glob("*.md"), reverse=True)
    pages: list[tuple[str, str, str]] = []
    for digest_file in digest_files:
        slug = digest_file.stem
        title = _title_from_markdown(digest_file.read_text(encoding="utf-8")) or f"Digest {slug}"
        html_path = digests_dir / f"{slug}.html"
        html_path.write_text(
            _page_html(
                title=title,
                body=_markdown_to_html(digest_file.read_text(encoding="utf-8")),
                current="digest",
            ),
            encoding="utf-8",
        )
        pages.append((slug, title, f"digests/{slug}.html"))

    latest_body = _latest_body(output_dir, pages)
    (site_dir / "index.html").write_text(
        _page_html(title="AI Marketing Digest", body=latest_body, current="home"),
        encoding="utf-8",
    )
    (site_dir / "archive.html").write_text(
        _page_html(title="Archive - AI Marketing Digest", body=_archive_body(pages), current="archive"),
        encoding="utf-8",
    )
    (site_dir / "style.css").write_text(_css(), encoding="utf-8")
    (site_dir / "feed.xml").write_text(_rss(pages), encoding="utf-8")
    return site_dir / "index.html"


def _latest_body(output_dir: Path, pages: list[tuple[str, str, str]]) -> str:
    if not pages:
        return """
        <section class="hero">
          <p class="eyebrow">Daily AI and marketing intelligence</p>
          <h1>AI Marketing Digest</h1>
          <p>No public digest has been generated yet.</p>
        </section>
        """

    slug, title, href = pages[0]
    markdown = (output_dir / f"{slug}.md").read_text(encoding="utf-8")
    return f"""
    <section class="hero">
      <p class="eyebrow">Daily AI and marketing intelligence</p>
      <h1>AI Marketing Digest</h1>
      <p>Recent AI and marketing signals, curated sources, and LinkedIn-ready ideas with a clear point of view.</p>
      <div class="actions">
        <a class="button" href="{html.escape(href)}">Read latest digest</a>
        <a class="button secondary" href="archive.html">Browse archive</a>
      </div>
    </section>
    <section class="digest-preview">
      {_markdown_to_html(markdown)}
    </section>
    """


def _archive_body(pages: list[tuple[str, str, str]]) -> str:
    items = "\n".join(
        f'<li><a href="{html.escape(href)}">{html.escape(title)}</a><span>{html.escape(slug)}</span></li>'
        for slug, title, href in pages
    )
    if not items:
        items = "<li>No digests yet.</li>"
    return f"""
    <section class="page-heading">
      <p class="eyebrow">Archive</p>
      <h1>Published Digests</h1>
    </section>
    <ol class="archive-list">
      {items}
    </ol>
    """


def _page_html(title: str, body: str, current: str) -> str:
    home_class = 'class="active"' if current == "home" else ""
    archive_class = 'class="active"' if current in {"archive", "digest"} else ""
    escaped_title = html.escape(title)
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="AI Marketing Digest: daily AI and marketing articles, signals, and LinkedIn-ready ideas.">
  <title>{escaped_title}</title>
  <link rel="stylesheet" href="{_style_path(current)}">
  <link rel="alternate" type="application/rss+xml" title="AI Marketing Digest RSS" href="{_rss_path(current)}">
</head>
<body>
  <header class="topbar">
    <a class="brand" href="{_root_path(current)}index.html">AI Marketing Digest</a>
    <nav>
      <a {home_class} href="{_root_path(current)}index.html">Latest</a>
      <a {archive_class} href="{_root_path(current)}archive.html">Archive</a>
      <a href="{_root_path(current)}feed.xml">RSS</a>
    </nav>
  </header>
  <main>
    {body}
  </main>
  <footer>
    <p>Generated by ai-marketing-digest. Sources are credited in each issue.</p>
  </footer>
</body>
</html>
"""


def _markdown_to_html(markdown: str) -> str:
    lines = markdown.splitlines()
    result: list[str] = []
    paragraph: list[str] = []
    in_list = False

    def flush_paragraph() -> None:
        nonlocal paragraph
        if paragraph:
            result.append(f"<p>{_inline(' '.join(paragraph))}</p>")
            paragraph = []

    def close_list() -> None:
        nonlocal in_list
        if in_list:
            result.append("</ul>")
            in_list = False

    for raw_line in lines:
        line = raw_line.rstrip()
        if not line:
            flush_paragraph()
            close_list()
            continue
        if line == "---":
            flush_paragraph()
            close_list()
            result.append("<hr>")
            continue
        heading = re.match(r"^(#{1,3})\s+(.+)$", line)
        if heading:
            flush_paragraph()
            close_list()
            level = len(heading.group(1))
            result.append(f"<h{level}>{_inline(heading.group(2))}</h{level}>")
            continue
        bullet = re.match(r"^-\s+(.+)$", line)
        if bullet:
            flush_paragraph()
            if not in_list:
                result.append("<ul>")
                in_list = True
            result.append(f"<li>{_inline(bullet.group(1))}</li>")
            continue
        paragraph.append(line)

    flush_paragraph()
    close_list()
    return "\n".join(result)


def _inline(text: str) -> str:
    escaped = html.escape(text)
    escaped = re.sub(
        r"(https?://[^\s<]+)",
        lambda match: f'<a href="{html.escape(match.group(1))}" rel="noopener noreferrer">{html.escape(match.group(1))}</a>',
        escaped,
    )
    escaped = re.sub(r"`([^`]+)`", r"<code>\1</code>", escaped)
    return escaped


def _title_from_markdown(markdown: str) -> str | None:
    for line in markdown.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return None


def _root_path(current: str) -> str:
    return "../" if current == "digest" else ""


def _style_path(current: str) -> str:
    return "../style.css" if current == "digest" else "style.css"


def _rss_path(current: str) -> str:
    return "../feed.xml" if current == "digest" else "feed.xml"


def _rss(pages: list[tuple[str, str, str]]) -> str:
    now = format_datetime(datetime.now(timezone.utc))
    items = []
    for slug, title, href in pages[:20]:
        link = quote(href, safe="/:.")
        items.append(
            f"""
    <item>
      <title>{html.escape(title)}</title>
      <link>{link}</link>
      <guid>{link}</guid>
      <pubDate>{now}</pubDate>
    </item>"""
        )
    return f"""<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0">
  <channel>
    <title>AI Marketing Digest</title>
    <description>Daily AI and marketing articles, signals, and LinkedIn-ready ideas.</description>
    <link>index.html</link>
    <lastBuildDate>{now}</lastBuildDate>
    {''.join(items)}
  </channel>
</rss>
"""


def _css() -> str:
    return """
:root {
  color-scheme: light;
  --bg: #f6f7f9;
  --ink: #17191f;
  --muted: #5d6472;
  --line: #dfe3ea;
  --panel: #ffffff;
  --accent: #0f766e;
  --accent-dark: #0b5d56;
}

* { box-sizing: border-box; }

body {
  margin: 0;
  background: var(--bg);
  color: var(--ink);
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  line-height: 1.58;
}

a { color: var(--accent-dark); }

.topbar {
  position: sticky;
  top: 0;
  z-index: 10;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 20px;
  padding: 16px clamp(18px, 4vw, 56px);
  border-bottom: 1px solid var(--line);
  background: rgba(246, 247, 249, 0.92);
  backdrop-filter: blur(10px);
}

.brand {
  color: var(--ink);
  font-weight: 800;
  text-decoration: none;
}

nav {
  display: flex;
  gap: 14px;
  flex-wrap: wrap;
}

nav a {
  color: var(--muted);
  text-decoration: none;
  font-weight: 650;
  font-size: 0.95rem;
}

nav a.active,
nav a:hover {
  color: var(--ink);
}

main {
  width: min(980px, calc(100% - 32px));
  margin: 0 auto;
  padding: 34px 0 64px;
}

.hero,
.page-heading {
  padding: clamp(34px, 8vw, 82px) 0 28px;
}

.hero h1,
.page-heading h1 {
  margin: 0;
  font-size: clamp(2.25rem, 7vw, 5.2rem);
  line-height: 0.98;
  max-width: 760px;
  letter-spacing: 0;
}

.hero p {
  max-width: 680px;
  color: var(--muted);
  font-size: 1.12rem;
}

.eyebrow {
  margin: 0 0 14px;
  color: var(--accent-dark);
  font-size: 0.82rem;
  font-weight: 800;
  letter-spacing: 0.08em;
  text-transform: uppercase;
}

.actions {
  display: flex;
  gap: 12px;
  flex-wrap: wrap;
  margin-top: 24px;
}

.button {
  display: inline-flex;
  align-items: center;
  min-height: 42px;
  padding: 10px 16px;
  border: 1px solid var(--accent);
  border-radius: 6px;
  background: var(--accent);
  color: white;
  text-decoration: none;
  font-weight: 750;
}

.button.secondary {
  background: transparent;
  color: var(--accent-dark);
}

.digest-preview,
.archive-list {
  padding: clamp(20px, 4vw, 34px);
  border: 1px solid var(--line);
  border-radius: 8px;
  background: var(--panel);
}

h1, h2, h3 {
  line-height: 1.16;
  letter-spacing: 0;
}

h2 {
  margin-top: 46px;
  padding-top: 10px;
  border-top: 1px solid var(--line);
}

h3 {
  margin-top: 30px;
}

ul {
  padding-left: 1.2rem;
}

li + li {
  margin-top: 8px;
}

hr {
  border: 0;
  border-top: 1px solid var(--line);
  margin: 34px 0;
}

code {
  padding: 2px 5px;
  border-radius: 4px;
  background: #eef1f5;
}

.archive-list {
  list-style: none;
  margin: 0;
  padding: 0;
}

.archive-list li {
  display: flex;
  justify-content: space-between;
  gap: 20px;
  padding: 18px 22px;
  border-bottom: 1px solid var(--line);
}

.archive-list li:last-child {
  border-bottom: 0;
}

.archive-list a {
  color: var(--ink);
  font-weight: 750;
  text-decoration: none;
}

.archive-list span,
footer {
  color: var(--muted);
}

footer {
  width: min(980px, calc(100% - 32px));
  margin: 0 auto;
  padding: 0 0 36px;
  font-size: 0.92rem;
}

@media (max-width: 680px) {
  .topbar {
    align-items: flex-start;
    flex-direction: column;
  }

  .archive-list li {
    flex-direction: column;
    gap: 4px;
  }
}
"""
